name: Lint Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  actionlint:
    uses: FasterSpeeding/Piped/.github/workflows/lint-actions.yml@5a4ad660b34fa197da9164a93df0e8a5482dccd7
    secrets: inherit
